#!/bin/bash

todo() {
    if [[ $1 == "init" ]]; then
        mkdir -p $HOME/todo_cli/todo
        mkdir -p $HOME/todo_cli/finished

    elif [[ $1 == "make" ]]; then
        touch "$HOME/todo_cli/todo/-$2"

    elif [[ $1 == "del" ]]; then
        rm "$HOME/todo_cli/todo/-$2"

    elif [[ $1 == "note" ]]; then
        vim "$HOME/todo_cli/todo/-$2"

    elif [[ $1 == "view" ]]; then
        if [[ $2 == "-a" ]]; then
            echo Current tasks:
            ls -N $HOME/todo_cli/todo/
            echo ==========
            echo Finished:
            ls -N $HOME/todo_cli/finished/
        else
            ls -N $HOME/todo_cli/todo/
        fi

    elif [[ $1 == "tag" ]]; then
        sed -i "1s|.*|#tag: $3|" "$HOME/todo_cli/todo/-$2"

    elif [[ $1 == "done" ]]; then
        mv "~/todo_cli/todo/-$2" "$HOME/todo_cli/fin/-$2"

    elif [[ $1 == "cleanup" ]]; then
        rm -f $HOME/todo_cli/fin/*
    else
        echo "Usage:"
        echo "  todo init"
        echo "  todo make <name>"
        echo "  todo del <name>"
        echo "  todo note <name>"
        echo "  todo view [-a]"
        echo "  todo tag <name> <tag>"
        echo "  todo done <name>"
        echo "  todo cleanup #delete finished todos"
    fi
}

todo "$@"
