#!/bin/bash

todo() {
    if [[ $1 == "init" ]]; then
        mkdir -p $HOME/todo_cli/todo
        mkdir -p $HOME/todo_cli/finished
        mkdir -p $HOME/todo_cli/data

        touch $HOME/todo_cli/data/tags
        touch $HOME/todo_cli/data/todos

    elif [[ $1 == "make" ]]; then
        shift

        for task in "$@"; do
            touch "$HOME/todo_cli/todo/-$task"
        done

    elif [[ $1 == "del" ]]; then
        shift

        for target in "$@"; do
            rm "$HOME/todo_cli/todo/-$target"
        done

    elif [[ $1 == "note" ]]; then
        vim "$HOME/todo_cli/todo/-$2"

    elif [[ $1 == "view" ]]; then
        if [[ $2 == "-a" ]]; then
            printf "==========\n"
            printf "\n\033[1;33mCurrent tasks:\033[0m\n"
            ls -1 -N $HOME/todo_cli/todo/
            
            printf "\n==========\n"

            printf "\n\033[1;32mFinished:\033[0m\n"
            ls -1 -N $HOME/todo_cli/finished/
            printf "\n==========\n"

        else
            printf "==========\n"
            printf "\n\033[1;33mCurrent tasks:\033[0m\n"
            ls -1 -N $HOME/todo_cli/todo/
            printf "\n==========\n"
        fi

    elif [[ $1 == "tag" ]]; then
        sed -i "1i\\
        #tag: $3
        " "$HOME/todo_cli/todo/-$2"

    elif [[ $1 == "done" ]]; then
        shift

        for task in "$@"; do
            mv "$HOME/todo_cli/todo/-$task" "$HOME/todo_cli/finished/-$task"
        done

    elif [[ $1 == "cleanup" ]]; then
        rm -f $HOME/todo_cli/finished/*
    else
        echo "Usage:"
        echo "  todo init"
        echo "  todo make <name>"
        echo "  todo del <name>"
        echo "  todo note <name>"
        echo "  todo view [-a]"
        echo "  todo tag <name> <tag>"
        echo "  todo done <name>"
        echo "  todo cleanup #delete finished todos"
    fi
}

todo "$@"
